# Generated by Django 4.2 on 2024-04-22 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_product_price_product_price_aed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_AED',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_EGP',
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('AED', 'AED'), ('EGP', 'EGP')], max_length=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'unique_together': {('product', 'currency')},
            },
        ),
    ]
