# Generated by Django 4.2 on 2024-04-28 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_brand_title_ar_brand_title_en_category_title_ar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Category'},
        ),
        migrations.RemoveField(
            model_name='brand',
            name='title',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title',
        ),
        migrations.RemoveField(
            model_name='color',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
        migrations.RemoveField(
            model_name='size',
            name='name',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='content',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='title',
        ),
    ]
