# Generated by Django 4.2 on 2024-04-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_category_options_remove_brand_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='title_en',
            field=models.CharField(max_length=100),
        ),
    ]
