# Generated by Django 4.2 on 2024-04-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_brand_title_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title_en',
            field=models.CharField(max_length=100),
        ),
    ]
