# Generated by Django 4.2 on 2024-04-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_product_title_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='currency',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='currency',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cartorderitem',
            name='currency',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
