# Generated by Django 4.2 on 2024-05-04 22:14

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_cart_currency_cartorder_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='cid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefg123456', blank=True, length=10, max_length=10, null=True, prefix=''),
        ),
        migrations.AddField(
            model_name='size',
            name='sid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefg123456', blank=True, length=10, max_length=10, null=True, prefix=''),
        ),
        migrations.AddField(
            model_name='specification',
            name='spid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefg123456', blank=True, length=10, max_length=10, null=True, prefix=''),
        ),
    ]
